### ISSUE TITLE
TraceBack 

### ISSUE THREAD

**Issue by Prolasis** [smart-on-fhir/client-py#76] opened 2019-08-06 16:46 UTC
![flask error](https://user-images.githubusercontent.com/14959836/62558971-0f93a080-b848-11e9-997b-866c09979990.PNG)
Cloned the repo didn't change anything and followed guide to setup a virtual environment. After launching i noticed it fails and throws trace error. See pic. ?

**Comment by Prolasis** [comment] 2019-08-06 17:56
Fixed issue by updating the beaker version see below. Please update 

**Beaker==1.10.0**
Flask==0.10.1
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.14.1
isodate==0.5.1
itsdangerous==0.24
requests==2.7.0

**Comment by mikix** [comment] 2024-07-16 13:41
Thanks for the report! But I'll close as a duplicate of #72

**Closed by mikix** 2024-07-16 13:41 UTC
